services:
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    ports:
      - 9216:9200
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=<replaceme>
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms6G -Xmx6G"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - "indices.breaker.total.limit=85%"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    deploy:
      resources:
        limits:
          memory: 16384M
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  models: {}
  opensearch_data: {}
